"""add attachment entity_id

Revision ID: 60ec8bad202b
Revises: 405c749934b5
Create Date: 2026-08-12 23:20:37.406730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ec8bad202b'
down_revision: Union[str, Sequence[str], None] = '405c749934b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('entity_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'entity_id')
    # ### end Alembic commands ###
