"""initial_schema_all_11_entities

Revision ID: f0b8febaf3b9
Revises: 
Create Date: 2026-08-26 17:46:33.269769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b8febaf3b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Archived', name='category_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('student_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('User', 'Officer', 'Administrator', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Suspended', 'Inactive', name='user_status'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('related_entity', sa.Enum('LostItem', 'FoundItem', 'Claim', name='related_entity'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('found_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('date_found', sa.Date(), nullable=False),
    sa.Column('storage_location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('Available', 'Claimed', 'Returned', name='found_item_status'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_found_items_category_id'), 'found_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_found_items_user_id'), 'found_items', ['user_id'], unique=False)
    op.create_table('lost_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('date_lost', sa.Date(), nullable=False),
    sa.Column('location_lost', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('Reported', 'Matched', 'Claimed', 'Closed', name='lost_item_status'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_items_category_id'), 'lost_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_lost_items_user_id'), 'lost_items', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.Enum('Match', 'Claim', 'Reminder', 'System', name='notification_type'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('lost_item_id', sa.Integer(), nullable=True),
    sa.Column('found_item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claim_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_status', sa.Enum('Pending', 'Approved', 'Rejected', name='claim_verification_status'), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('collection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Completed', 'Cancelled', name='claim_status'), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_found_item_id'), 'claims', ['found_item_id'], unique=False)
    op.create_index(op.f('ix_claims_lost_item_id'), 'claims', ['lost_item_id'], unique=False)
    op.create_index(op.f('ix_claims_user_id'), 'claims', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.Column('found_item_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Suggested', 'Accepted', 'Rejected', name='match_status'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lost_item_id', 'found_item_id', name='uq_matches_lost_item_found_item')
    )
    op.create_index(op.f('ix_matches_found_item_id'), 'matches', ['found_item_id'], unique=False)
    op.create_index(op.f('ix_matches_lost_item_id'), 'matches', ['lost_item_id'], unique=False)
    op.create_table('collection_records',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('collected_by', sa.String(length=200), nullable=True),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('collection_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recipient_signature', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_records_claim_id'), 'collection_records', ['claim_id'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('verification_method', sa.String(length=100), nullable=True),
    sa.Column('result', sa.Enum('Passed', 'Failed', name='verification_result'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_claim_id'), 'verification_records', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_records_claim_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_collection_records_claim_id'), table_name='collection_records')
    op.drop_table('collection_records')
    op.drop_index(op.f('ix_matches_lost_item_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_found_item_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_claims_user_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_lost_item_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_found_item_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_lost_items_user_id'), table_name='lost_items')
    op.drop_index(op.f('ix_lost_items_category_id'), table_name='lost_items')
    op.drop_table('lost_items')
    op.drop_index(op.f('ix_found_items_user_id'), table_name='found_items')
    op.drop_index(op.f('ix_found_items_category_id'), table_name='found_items')
    op.drop_table('found_items')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
