"""Initial schema: all 11 entities

Revision ID: ff0a486902ce
Revises: 
Create Date: 2026-08-25 14:51:41.084201

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff0a486902ce'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Archived', name='categorystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('student_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('User', 'Officer', 'Administrator', name='role'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Suspended', 'Inactive', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('attachment',
    sa.Column('attachment_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('related_entity', sa.Enum('LostItem', 'FoundItem', 'Claim', name='relatedentity'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_name'), 'audit_log', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('found_item',
    sa.Column('found_item_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('date_found', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Claimed', 'Returned', name='founditemstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('found_item_id')
    )
    op.create_index(op.f('ix_found_item_category_id'), 'found_item', ['category_id'], unique=False)
    op.create_index(op.f('ix_found_item_user_id'), 'found_item', ['user_id'], unique=False)
    op.create_table('lost_item',
    sa.Column('lost_item_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('date_lost', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_lost', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Reported', 'Matched', 'Claimed', 'Closed', name='lostitemstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lost_item_id')
    )
    op.create_index(op.f('ix_lost_item_category_id'), 'lost_item', ['category_id'], unique=False)
    op.create_index(op.f('ix_lost_item_user_id'), 'lost_item', ['user_id'], unique=False)
    op.create_table('notification',
    sa.Column('notification_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('Match', 'Claim', 'Reminder', 'System', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('claim',
    sa.Column('claim_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lost_item_id', sa.UUID(), nullable=True),
    sa.Column('found_item_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('claim_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_status', sa.Enum('Pending', 'Approved', 'Rejected', name='verificationstatus'), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('collection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Completed', 'Cancelled', name='claimstatus'), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_item.found_item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_item.lost_item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['officer_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_index(op.f('ix_claim_found_item_id'), 'claim', ['found_item_id'], unique=False)
    op.create_index(op.f('ix_claim_lost_item_id'), 'claim', ['lost_item_id'], unique=False)
    op.create_index(op.f('ix_claim_user_id'), 'claim', ['user_id'], unique=False)
    op.create_table('match',
    sa.Column('match_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lost_item_id', sa.UUID(), nullable=False),
    sa.Column('found_item_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Suggested', 'Accepted', 'Rejected', name='matchstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['found_item.found_item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_item.lost_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_match_found_item_id'), 'match', ['found_item_id'], unique=False)
    op.create_index(op.f('ix_match_lost_item_id'), 'match', ['lost_item_id'], unique=False)
    op.create_table('collection_record',
    sa.Column('collection_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('collected_by', sa.String(length=200), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('collection_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recipient_signature', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.claim_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_index(op.f('ix_collection_record_claim_id'), 'collection_record', ['claim_id'], unique=False)
    op.create_table('verification_record',
    sa.Column('verification_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('verification_method', sa.String(length=100), nullable=False),
    sa.Column('result', sa.Enum('Passed', 'Failed', name='verificationresult'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.claim_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_index(op.f('ix_verification_record_claim_id'), 'verification_record', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_record_claim_id'), table_name='verification_record')
    op.drop_table('verification_record')
    op.drop_index(op.f('ix_collection_record_claim_id'), table_name='collection_record')
    op.drop_table('collection_record')
    op.drop_index(op.f('ix_match_lost_item_id'), table_name='match')
    op.drop_index(op.f('ix_match_found_item_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_claim_user_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_lost_item_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_found_item_id'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_lost_item_user_id'), table_name='lost_item')
    op.drop_index(op.f('ix_lost_item_category_id'), table_name='lost_item')
    op.drop_table('lost_item')
    op.drop_index(op.f('ix_found_item_user_id'), table_name='found_item')
    op.drop_index(op.f('ix_found_item_category_id'), table_name='found_item')
    op.drop_table('found_item')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
